---
- name: Crear directorio de configuración para vmauth
  file:
    path: /etc/anomalia/vmauth
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Crear archivo de configuración de vmauth desde plantilla
  template:
    src: vmauth.yml.j2
    dest: /etc/anomalia/vmauth/config.yml
    mode: '0644'
  notify: Recargar systemd y reiniciar vmauth

- name: Copiar servicio systemd de anomalia vmauth
  template:
    src: vmauth.service.server.j2
    dest: /etc/systemd/system/anomalia-vmauth.service
    mode: '0644'
  notify: Recargar systemd y reiniciar vmauth
