---
- name: Recargar systemd y reiniciar vtstorage
  systemd:
    daemon_reload: yes
    name: anomalia-vtstorage
    state: restarted

- name: Recargar systemd y reiniciar vtinsert
  systemd:
    daemon_reload: yes
    name: anomalia-vtinsert
    state: restarted

- name: Recargar systemd y reiniciar vtselect
  systemd:
    daemon_reload: yes
    name: anomalia-vtselect
    state: restarted
