---
- name: Recargar systemd, Habilitar y levantar alertmanager
  block:
    - name: Recargar demonio de systemd
      command: sudo systemctl daemon-reload

    - name: Habilitar anomalia-alertmanager
      command: sudo systemctl enable --now anomalia-alertmanager.service

    - name: Habilitar 
      command: sudo systemctl enable --now anomalia-alertmanager.service

    - name: Arrancar anomalia-alertmanager
      command: sudo systemctl start anomalia-alertmanager.service

