---
- name: Crear directorios de datos para Pyroscope
  file:
    path: "{{ pyroscope_storage_path }}"
    state: directory
    mode: '0755'

- name: Copiar servicio systemd para Pyroscope
  template:
    src: pyroscope.service.j2
    dest: /etc/systemd/system/anomalia-pyroscope.service
    mode: '0644'
  notify: Recargar systemd y reiniciar pyroscope
