---
- name: Crear directorios de almacenamiento para Anomalia Logs
  file:
    path: "{{ vlstorage_path }}"
    state: directory
    mode: '0755'

- name: Copiar servicio systemd de anomalia vlstorage
  template:
    src: vlstorage.service.j2
    dest: /etc/systemd/system/anomalia-vlstorage.service
    mode: '0644'
  notify: Recargar systemd y reiniciar vlstorage

- name: Copiar servicio systemd de anomalia vlinsert
  template:
    src: vlinsert.service.j2
    dest: /etc/systemd/system/anomalia-vlinsert.service
    mode: '0644'
  notify: Recargar systemd y reiniciar vlinsert

- name: Copiar servicio systemd de anomalia vlselect
  template:
    src: vlselect.service.j2
    dest: /etc/systemd/system/anomalia-vlselect.service
    mode: '0644'
  notify: Recargar systemd y reiniciar vlselect
