# =====================================================================
# Configuración de Endpoints para vmauth
# =====================================================================

# 1. Obtenemos el nodo, puerto e IP específica definida en el inventario para vmauth
backend_vmauth_node: "{{ groups['vmauth_nodes'][0] }}"
backend_vmauth_ip: "{{ hostvars[backend_vmauth_node].vmauth_ip | default('127.0.0.1') }}"
backend_vmauth_port: "{{ hostvars[backend_vmauth_node].vmauth_port | default('8427') }}"

# 2. Asignación directa a la IP real de escucha (ej. 192.168.1.27) 
backend_vmauth_base_url: "http://{{ backend_vmauth_ip }}:{{ backend_vmauth_port }}"

# 3. Endpoints finales que consumirá el backend
backend_pyroscope_address: "{{ backend_vmauth_base_url }}"
backend_otel_traces_endpoint: "{{ backend_vmauth_base_url }}/insert/opentelemetry/v1/traces?tenant=TRACES"
backend_otel_metrics_endpoint: "{{ backend_vmauth_base_url }}/insert/opentelemetry/v1/metrics?tenant=METRICS"
backend_audit_logs_endpoint: "{{ backend_vmauth_base_url }}/insert/loki/api/v1/push?tenant=AUDIT_LOGS"
