---
- name: Crear directorios de almacenamiento para Anomalia Traces
  file:
    path: "{{ vtstorage_path }}"
    state: directory
    mode: '0755'
  when: inventory_hostname in groups.get('vt_storage_nodes', [])

- name: Copiar servicio systemd de anomalia vtstorage
  template:
    src: vtstorage.service.j2
    dest: /etc/systemd/system/anomalia-vtstorage.service
    mode: '0644'
  notify: Recargar systemd y reiniciar vtstorage
  when: inventory_hostname in groups.get('vt_storage_nodes', [])

- name: Copiar servicio systemd de anomalia vtinsert
  template:
    src: vtinsert.service.j2
    dest: /etc/systemd/system/anomalia-vtinsert.service
    mode: '0644'
  notify: Recargar systemd y reiniciar vtinsert
  when: inventory_hostname in groups.get('vt_insert_nodes', [])

- name: Copiar servicio systemd de anomalia vtselect
  template:
    src: vtselect.service.j2
    dest: /etc/systemd/system/anomalia-vtselect.service
    mode: '0644'
  notify: Recargar systemd y reiniciar vtselect
  when: inventory_hostname in groups.get('vt_select_nodes', [])
