---
- name: Crear directorios de datos para Anomalia Alertmanager
  file:
    path: "{{ alertmanager_storage_path }}"
    state: directory
    mode: '0755'

- name: Crear directorio de configuracion para Anomalia Alertmanager
  file:
    path: /etc/anomalia/alertmanager
    state: directory
    mode: '0755'

- name: Copiar archivo de configuracion alertmanager.yml
  template:
    src: alertmanager.yml.j2
    dest: /etc/anomalia/alertmanager/alertmanager.yml
    mode: '0644'
  notify: Reiniciar alertmanager

- name: Copiar servicio systemd de anomalia alertmanager
  template:
    src: alertmanager.service.j2
    dest: /etc/systemd/system/anomalia-alertmanager.service
    mode: '0644'
  notify: Recargar systemd y reiniciar alertmanager
